In [1]:
import pandas as pd

In [2]:
def compare_dataframes(df1, df2, key1="HPO_IRI", key2="phenotype_iri"):
    """
    Compare two DataFrames and identify rows that are unique to each.

    This function performs an outer merge between two DataFrames on the 
    specified key columns, then returns the rows that exist only in df1 
    or only in df2.

    Parameters
    ----------
    df1 : pd.DataFrame
        The first DataFrame to compare.
    df2 : pd.DataFrame
        The second DataFrame to compare.
    key1 : str, optional
        The column name in df1 used for merging. Default is 'HPO_IRI'.
    key2 : str, optional
        The column name in df2 used for merging. Default is 'phenotype_iri'.

    Returns
    -------
    distinct_in_df1 : pd.DataFrame
        Rows that are present only in df1.
    distinct_in_df2 : pd.DataFrame
        Rows that are present only in df2.

    """

    # Merge both DataFrames on their key columns
    merged = df1.merge(
        df2,
        left_on=[key1],
        right_on=[key2],
        how='outer',
        indicator=True
    )

    # Identify rows unique to each DataFrame
    distinct_in_df1 = merged[merged['_merge'] == 'left_only'].drop(columns='_merge')
    distinct_in_df2 = merged[merged['_merge'] == 'right_only'].drop(columns='_merge')

    # Print a quick summary for convenience
    print(f"Unique in df1: {len(distinct_in_df1)} rows")
    print(f"Unique in df2: {len(distinct_in_df2)} rows")

    return distinct_in_df1, distinct_in_df2

In [3]:
bruce_file = pd.read_csv("../../data/outputs/BRUCE_hpo-asct-data.csv")

In [4]:
bruce_file

,phenotype_iri,phenotype_label,as_child,ct
0,http://purl.obolibrary.org/obo/HP_0000002,Abnormality of body height,http://purl.obolibrary.org/obo/UBERON_0000468,NaN
1,http://purl.obolibrary.org/obo/HP_0000008,Abnormal morphology of female internal genitalia,http://purl.obolibrary.org/obo/UBERON_0003975,NaN
2,http://purl.obolibrary.org/obo/HP_0000009,Functional abnormality of the bladder,http://purl.obolibrary.org/obo/UBERON_0001255,NaN
3,http://purl.obolibrary.org/obo/HP_0000013,Hypoplasia of the uterus,http://purl.obolibrary.org/obo/UBERON_0000995,NaN
4,http://purl.obolibrary.org/obo/HP_0000014,Abnormality of the bladder,http://purl.obolibrary.org/obo/UBERON_0001255,NaN
...,...,...,...,...
5922,http://purl.obolibrary.org/obo/HP_6000234,Elevated circulating dihydroxyphenylacetic aci...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5923,http://purl.obolibrary.org/obo/HP_6000267,Elevated circulating methionine sulfoxide conc...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5924,http://purl.obolibrary.org/obo/HP_6000268,Elevated circulating pipecolic acid concentration,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5925,http://purl.obolibrary.org/obo/HP_6000271,Elevated circulating glycylproline concentration,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5926,http://purl.obolibrary.org/obo/HP_6000278,Elevated circulating 2-aminoadipic acid concen...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN

In [5]:
bruce_file_uberon = bruce_file.dropna(subset=['as_child'])

In [6]:
bruce_file_uberon

,phenotype_iri,phenotype_label,as_child,ct
0,http://purl.obolibrary.org/obo/HP_0000002,Abnormality of body height,http://purl.obolibrary.org/obo/UBERON_0000468,NaN
1,http://purl.obolibrary.org/obo/HP_0000008,Abnormal morphology of female internal genitalia,http://purl.obolibrary.org/obo/UBERON_0003975,NaN
2,http://purl.obolibrary.org/obo/HP_0000009,Functional abnormality of the bladder,http://purl.obolibrary.org/obo/UBERON_0001255,NaN
3,http://purl.obolibrary.org/obo/HP_0000013,Hypoplasia of the uterus,http://purl.obolibrary.org/obo/UBERON_0000995,NaN
4,http://purl.obolibrary.org/obo/HP_0000014,Abnormality of the bladder,http://purl.obolibrary.org/obo/UBERON_0001255,NaN
...,...,...,...,...
5922,http://purl.obolibrary.org/obo/HP_6000234,Elevated circulating dihydroxyphenylacetic aci...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5923,http://purl.obolibrary.org/obo/HP_6000267,Elevated circulating methionine sulfoxide conc...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5924,http://purl.obolibrary.org/obo/HP_6000268,Elevated circulating pipecolic acid concentration,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5925,http://purl.obolibrary.org/obo/HP_6000271,Elevated circulating glycylproline concentration,http://purl.obolibrary.org/obo/UBERON_0000178,NaN
5926,http://purl.obolibrary.org/obo/HP_6000278,Elevated circulating 2-aminoadipic acid concen...,http://purl.obolibrary.org/obo/UBERON_0000178,NaN

## compare with the file including the hierarchical recursion

In [7]:
df_uberon = pd.read_csv("../../data/outputs/hpo_to_uberon_links.csv")

In [8]:
distinct_mine, distinct_bruce = compare_dataframes(df_uberon, bruce_file_uberon)

Unique in df1: 55484 rows
Unique in df2: 0 rows

In [9]:
distinct_mine

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label,phenotype_iri,phenotype_label,as_child,ct
1,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN,NaN,NaN,NaN,NaN
2,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002113,kidney,False,NaN,NaN,NaN,NaN,NaN,NaN
3,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0011143,upper urinary tract,False,NaN,NaN,NaN,NaN,NaN,NaN
4,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001008,renal system,False,NaN,NaN,NaN,NaN,NaN,NaN
5,http://purl.obolibrary.org/obo/HP_0000003,Multicystic kidney dysplasia,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0004122,genitourinary system,False,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
123613,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002114,duodenum,False,NaN,NaN,NaN,NaN,NaN,NaN
123614,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0002108,small intestine,False,NaN,NaN,NaN,NaN,NaN,NaN
123615,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0000160,intestine,False,NaN,NaN,NaN,NaN,NaN,NaN
123616,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0005409,alimentary part of gastrointestinal system,False,NaN,NaN,NaN,NaN,NaN,NaN
123617,http://purl.obolibrary.org/obo/HP_6001337,White appearance of duodenal mucosa,characteristic of part of,http://purl.obolibrary.org/obo/UBERON_0001007,digestive system,False,NaN,NaN,NaN,NaN,NaN,NaN

## compare with the file without the hierarchical recursion

In [12]:
df_uberon_witho_hierarchy = pd.read_csv("../../data/outputs/hpo_to_uberon_links_witho_hierarchy.csv")

In [13]:
distinct_mine_witho_hierarchy, distinct_bruce_witho_hierarchy = compare_dataframes(df_uberon_witho_hierarchy, bruce_file_uberon)

Unique in df1: 86 rows
Unique in df2: 2 rows

In [14]:
distinct_bruce_witho_hierarchy

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label,phenotype_iri,phenotype_label,as_child,ct
660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://purl.obolibrary.org/obo/HP_0001561,Polyhydramnios,http://purl.obolibrary.org/obo/UBERON_0000173,NaN
3929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://purl.obolibrary.org/obo/HP_0010897,Hypersarcosinuria,http://purl.obolibrary.org/obo/UBERON_0001088,NaN

In [15]:
distinct_mine_witho_hierarchy

,HPO_IRI,HPO_Label,Property,Filler_IRI,Filler_Label,Obsolete,Replacement_IRI,Replacement_Label,phenotype_iri,phenotype_label,as_child,ct
15,http://purl.obolibrary.org/obo/HP_0000027,Azoospermia,part of,http://purl.obolibrary.org/obo/UBERON_0001968,semen,False,NaN,NaN,NaN,NaN,NaN,NaN
783,http://purl.obolibrary.org/obo/HP_0001880,Increased total eosinophil count,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
784,http://purl.obolibrary.org/obo/HP_0001882,Decreased total leukocyte count,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
786,http://purl.obolibrary.org/obo/HP_0001888,Decreased total lymphocyte count,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
787,http://purl.obolibrary.org/obo/HP_0001894,Thrombocytosis,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5795,http://purl.obolibrary.org/obo/HP_0410396,Increased central memory CD8+ T cell proportion,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
5940,http://purl.obolibrary.org/obo/HP_0500265,Increased proportion of CD8+ TEMRA T cells,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
5941,http://purl.obolibrary.org/obo/HP_0500266,Decreased proportion of CD8+ TEMRA T cells,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
5942,http://purl.obolibrary.org/obo/HP_0500270,Increased gamma-delta T cell proportion,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN
5943,http://purl.obolibrary.org/obo/HP_0500271,Decreased gamma-delta T cell proportion,part of,http://purl.obolibrary.org/obo/UBERON_0000178,blood,False,NaN,NaN,NaN,NaN,NaN,NaN